#!/usr/bin/python

"""Amulet tests on a basic Glance deployment on utopic-juno."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='utopic')
    deployment.run_tests()
