#!/usr/bin/python

"""Amulet tests on a basic glance deployment on trusty-mitaka."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='trusty',
                                         openstack='cloud:trusty-mitaka',
                                         source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
