#!/usr/bin/python

"""Amulet tests on a basic Glance deployment on xenial-mitaka."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='xenial')
    deployment.run_tests()
