#!/usr/bin/python

"""Amulet tests on a basic glance deployment on precise-essex."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='precise')
    deployment.run_tests()
