#!/usr/bin/python

"""Amulet tests on a basic glance deployment on precise-folsom."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='precise',
                                         openstack='cloud:precise-folsom',
                                         source='cloud:precise-updates/folsom')
    deployment.run_tests()
