#!/usr/bin/python

"""Amulet tests on a basic glance deployment on precise-grizzly."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='precise',
                                         openstack='cloud:precise-grizzly',
                                         source='cloud:precise-updates/grizzly')
    deployment.run_tests()
