#!/usr/bin/python

"""Amulet tests on a basic glance deployment on precise-havana."""

from basic_deployment import GlanceBasicDeployment

if __name__ == '__main__':
    deployment = GlanceBasicDeployment(series='precise',
                                         openstack='cloud:precise-havana',
                                         source='cloud:precise-updates/havana')
    deployment.run_tests()
