#!/bin/bash

CHARM="glance"

SERVICES="glance-api glance-registry"
PACKAGES="glance python-mysqldb python-swift python-keystone uuid"

GLANCE_REGISTRY_CONF="/etc/glance/glance-registry.conf"
GLANCE_REGISTRY_PASTE_INI="/etc/glance/glance-registry-paste.ini"
GLANCE_API_CONF="/etc/glance/glance-api.conf"
GLANCE_API_PASTE_INI="/etc/glance/glance-api-paste.ini"
CONF_DIR="/etc/glance"

if [[ -e "$CHARM_DIR/lib/openstack-common" ]] ; then
  . $CHARM_DIR/lib/openstack-common
else
  juju-log "ERROR: Couldn't load $CHARM_DIR/lib/openstack-common." && exit 1
fi

function set_or_update {
  local key="$1"
  local value="$2"
  local file="$3"
  local section="$4"
  local conf=""
  [[ -z $key ]] && juju-log "ERROR: set_or_update(): value $value missing key" \
        && exit 1
  [[ -z $value ]] && juju-log "ERROR: set_or_update(): key $key missing value" \
        && exit 1
  case "$file" in
    "api") conf=$GLANCE_API_CONF ;;
    "api-paste") conf=$GLANCE_API_PASTE_INI ;;
    "registry") conf=$GLANCE_REGISTRY_CONF ;;
    "registry-paste") conf=$GLANCE_REGISTRY_PASTE_INI ;;
    *) juju-log "ERROR: set_or_update(): Invalid or no config file specified." \
        && exit 1 ;;
  esac
  [[ ! -e $conf ]] && juju-log "ERROR: set_or_update(): File not found $conf" \
        && exit 1
  cfg_set_or_update "$key" "$value" "$conf" "$section"
}

do_openstack_upgrade() {
  # update openstack components to those provided by a new installation source
  # it is assumed the calling hook has confirmed that the upgrade is sane.
  local rel="$1"
  shift
  local packages=$@
  orig_os_rel=$(get_os_codename_package "glance-common")
  new_rel=$(get_os_codename_install_source "$rel")

  # Backup the config directory.
  local stamp=$(date +"%Y%m%d%M%S")
  tar -pcf /var/lib/juju/$CHARM-backup-$stamp.tar $CONF_DIR

  # Setup apt repository access and kick off the actual package upgrade.
  configure_install_source "$rel"
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get --option Dpkg::Options::=--force-confnew -y \
     install --no-install-recommends $packages

  # Update the new config files for existing relations.
  local r_id=""

  r_id=$(relation-ids shared-db)
  if [[ -n "$r_id" ]] ; then
    juju-log "$CHARM: Configuring database after upgrade to $rel."
    db_changed $r_id
  fi

  r_id=$(relation-ids identity-service)
  if [[ -n "$r_id" ]] ; then
    juju-log "$CHARM: Configuring identity service after upgrade to $rel."
    keystone_changed $r_id
  fi
}
